import PDFDocument from 'pdfkit';
import { Payslip } from './payslip.service';

export class PdfGeneratorService {
  static async generatePayslipPdf(payslip: Payslip): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const buffers: Buffer[] = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => {
          const pdfData = Buffer.concat(buffers);
          resolve(pdfData);
        });

        // Header
        doc.fontSize(20).text('PeoplePay360 Payslip', { align: 'center' });
        doc.moveDown();
        doc.fontSize(12).text(`Payslip ID: #${payslip.id}`);
        doc.text(`Status: ${payslip.status}`);
        doc.text(`Employee ID: ${payslip.employee_id}`);
        doc.moveDown();
        
        // Totals
        doc.fontSize(14).text('Summary', { underline: true });
        doc.fontSize(12).text(`Basic Wage: $${payslip.basic_wage}`);
        doc.text(`Gross Wage: $${payslip.gross_wage}`);
        doc.text(`Net Wage: $${payslip.net_wage}`);
        doc.moveDown();

        // Lines
        if (payslip.lines && payslip.lines.length > 0) {
          doc.fontSize(14).text('Earnings & Deductions', { underline: true });
          doc.moveDown();
          
          payslip.lines.forEach(line => {
            const prefix = line.category === 'DEDUCTION' ? '-' : '+';
            doc.fontSize(12).text(`${line.name} (${line.code}): ${prefix}$${line.amount}`);
          });
        }

        doc.moveDown(2);
        doc.fontSize(10).text('Generated by PeoplePay360 System', { align: 'center', color: 'grey' });
        
        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }
}
